[package]
name = "update_client"
version = "0.1.0"
authors = ["Robert Helmer <rhelmer@rhelmer.org>"]

[dependencies]
hyper = "0.11.0"
futures = "0.1.14"
tokio-core = "0.1.8"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
